### ISSUE TITLE
Option `forward: false` doesn't work out of the box

### ISSUE THREAD

**Issue by AdrianSandu** [scottalguire/grouploop#1]
Hi! I am using your script to animate a series of Bootstrap cards and I noticed that the `forward: false` option causes an error at line 112:

https://github.com/scottalguire/grouploop/blob/3a3fecb39fe2d99d79c246e4a0fd750925b1506e/src/grouploop-1.0.1.js#L112

The script is looking for the `transform` property which doesn't exist by default.

My workaround has been to add a dummy translation to the child wrapper element:

```
<div class="slider-rail" style="transform: translateX(0)">...</div>
```

**Comment by scottalguire** [comment]
Hey Adrian! Thanks for reporting the bug.

I've added a conditional to check whether there is an initial transform value on the child wrapper before it sets the value of curXPos. I tested your use case and it appears to be working.

See commit: [f531bb3](https://github.com/scottalguire/grouploop/commit/f531bb37ab98a820e691aef1a077eeaa8e6269bf)

**Comment by AdrianSandu** [comment]
Hi Scott! Many thanks for the prompt reply and fix.
